#!/usr/bin/env node

var program = require('commander');
var Multicall = require('@makerdao/multicall');
var Spinner = require('cli-spinner').Spinner;
var Table = require('cli-table');

var spinner = new Spinner(
  `Fetching polls from ${process.env.NETWORK}... %s 🚀  `
);
var multicall = new Multicall(process.env.NETWORK);
var toAddress = require('./conf/addresses')[process.env.NETWORK];
var tableChars = require('./conf/table').chars;

spinner.setSpinnerString(19);
spinner.start();

multicall
  .aggregate([
    {
      to: toAddress,
      method: `totalSupply()`,
      returns: [['gemSupply', 'uint256']]
    }
  ])
  .then(function(returnObject) {
    spinner.stop(false);
    console.log();
    var table = new Table({
      chars: tableChars,
      head: ['ID', 'Start', 'End', 'Num Choices', 'Status', 'Creator']
    });
    table.push(
      [
        '0',
        `${(Number(returnObject.gemSupply) / 10 ** 18).toLocaleString()} MKR`,
        '1',
        '2',
        '2',
        '3'
      ],
      [
        '1',
        `${(Number(returnObject.gemSupply) / 10 ** 18).toLocaleString()} MKR`,
        '1',
        '2',
        '2',
        '3'
      ]
    );

    console.log(table.toString());
  });

program.parse(process.argv);
