#!/usr/bin/env node

var program = require('commander');
var chalk = require('chalk');

if (process.env.NETWORK !== 'kovan' && process.env.NETWORK !== 'mainnet') {
  console.log(
    chalk.yellow(
      'NETWORK environment variable must be set to "mainnet" or "kovan"'
    )
  );
  console.log(chalk.italic('eg run > export NETWORK=mainnet'));
} else {
  program
    .version('0.1.0')
    .description('cli for interacting with the polling smart contract')
    .command('polls', 'list all created polls')
    // .command('tally [id]', 'get the current tally for a poll')
    // .command('check [id] [lad]', 'check a voters current pick for a poll')
    .parse(process.argv);
}
